server:
  port: 8764
  servlet:
    contextPath: /validation

spring:
  application:
    name: validation-service

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/