eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
  servlet:
    contextPath: /feign
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: feign-service
